# -*- coding: utf-8 -*-
"""sentiment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10YE1IfyFY1qViJ5GHNWRy5f2nTtbClJ2
"""

import sys

def clean_text(text):
    token = text.split()
    clean_text = []
    word = ""

    for a in token:
        for char in a:
            if char.isalpha():
                word += char
        if word:
            clean_text.append(word.lower())
            word = ""

    return clean_text


def read_file(filename):

    with open(filename, "r", encoding="utf-8") as f:
        sentiment_weights = {}
        next(f)
        for line in f:
            word, score = line.strip().split(",")
            sentiment_weights[word] = int(score)
        return sentiment_weights


def calculate_score(text, sentiment_weights):
    score = 0
    for word in sentiment_weights:
      if word in text:
        score += sentiment_weights[word]
    return score



def analyze_sentiment(document, sentiment_weights):
    results = []

    for text in document:
        tokens = clean_text(text)
        score = calculate_score(tokens, sentiment_weights)

        if score > 0:
            sentiments = "Positive"
        elif score < 0:
            sentiments = "Negative"
        else:
            sentiments = "Neutral"

        results.append({ "text": text, "score": score, "sentiments": sentiments })

    return results



def print_report(results, n = None):

    header = ["Post Content" , "Score" , "Sentiment"]
    length = 60
    line =  '-' * 60
    print(header[0].ljust(length),"|",  header[1], "|", header[2])
    print(line)

    if n == None:
        for item in results:
            print(item["text"].ljust(length),"|",item["score"], "|", item["sentiments"])
    else:
        for item in results[:n]:
            print(item["text"].ljust(length),"|",item["score"], "|", item["sentiments"])



def main():

    with open(sys.argv[2]) as f:
        reviews = f.readlines()
    sentiment_weights = read_file(sys.argv[1])
    results = analyze_sentiment(reviews, sentiment_weights)
    if len(sys.argv) > 3:
        input = sys.argv[3]

    if len(sys.argv) < 4:
        print_report(results, n = None)

    elif input.isdigit():
         print_report(results, int(input))

    elif input == "POS":
        pos = []
        for p in results:
            if p["sentiments"] == "Positive":
                pos.append(p)
            print_report(pos)

    elif input == "NEG":
        neg = []
        for p in results:
            if p["sentiments"] == "Negative":
                neg.append(p)
        print_report(neg)

    elif input == "NEUT":
        neu = []
        for p in results:
            if p["sentiments"] == "Neutral":
                neu.append(p)
        print_report(neu)

    else:
         print("Not supported")


if __name__=="__main__":
    main()

