# -*- coding: utf-8 -*-
"""sentiment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10YE1IfyFY1qViJ5GHNWRy5f2nTtbClJ2
"""

import sys

def clen_text(text)
    token = text.split()
    clean_text = []
    word = ""

    for a in token:
        for char in a:
            if char.isalpha():
                word += char
        if word:
            clean_text.append(word.lower())
            word = ""

    return clean_text


def read_file(filename)

    with open(filename, "r", encoding="utf-8") as f:
        sentiment_weights = {}
    next(f)
    for line in f:
        words, score = line.strip().split()
        return sentiment_weights


def calculate_score(text, sentiment_weights):
    score = 0
    for word in sentiment_weights:
      if word in text:
        score += sentiment_weights[word]
    return score



def analyze_sentiment(document, sentiment_weights):
    resluts = []

    if score > 0:
        sentiments = Positive
    elif score < 0:
        sentiments = Negative
    else
        sentiments = Neutral

    return results, score, sentiments



def print_report(results, n = None):

    header = ["Post Content" , "Score" , "Sentiment"]
    length = 60
    line =  '-' * 60
    print(header[0].ljust(length),"|",  header[1], "|", header[2])
    print(line)

    if n == None:
        for item in results:
            print(item["text"].ljust(),"|",item["score"], "|", item["sentiments"])
    else:
        for item in results[:n]:
            print(item["text"].ljust(),"|",item["score"], "|", item["sentiments"])

def main():








  if __name__=="__main__":
    main()

